// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dsstats.db;

#nullable disable

namespace dsstats.migrations.sqlite.Migrations
{
    [DbContext(typeof(DsstatsContext))]
    [Migration("20260128025509_FindDuplicateReplaysInRange")]
    partial class FindDuplicateReplaysInRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("DsAbilityDsUnit", b =>
                {
                    b.Property<int>("AbilitiesDsAbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DsUnitsDsUnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbilitiesDsAbilityId", "DsUnitsDsUnitId");

                    b.HasIndex("DsUnitsDsUnitId");

                    b.ToTable("DsAbilityDsUnit");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplay", b =>
                {
                    b.Property<int>("ArcadeReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BnetBucketId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BnetRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArcadeReplayId");

                    b.HasIndex("CreatedAt", "ArcadeReplayId")
                        .IsDescending(false, true);

                    b.HasIndex("RegionId", "BnetBucketId", "BnetRecordId")
                        .IsUnique();

                    b.ToTable("ArcadeReplays");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayPlayer", b =>
                {
                    b.Property<int>("ArcadeReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArcadeReplayPlayerId");

                    b.HasIndex("ArcadeReplayId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ArcadeReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayRating", b =>
                {
                    b.Property<int>("ArcadeReplayRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvgRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedWinProbability")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("PlayerRatingDeltas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PlayerRatings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArcadeReplayRatingId");

                    b.HasIndex("ArcadeReplayId");

                    b.ToTable("ArcadeReplayRatings");
                });

            modelBuilder.Entity("dsstats.db.CombinedReplay", b =>
                {
                    b.Property<int>("CombinedReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArcadeReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("CombinedReplayId");

                    b.HasIndex("ArcadeReplayId")
                        .IsUnique();

                    b.HasIndex("Gametime");

                    b.HasIndex("Imported");

                    b.HasIndex("ReplayId")
                        .IsUnique();

                    b.ToTable("CombinedReplays");
                });

            modelBuilder.Entity("dsstats.db.MauiConfig", b =>
                {
                    b.Property<int>("MauiConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppGuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoDecode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CPUCores")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CheckForUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IgnoreReplays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayStartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadAskTime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UploadCredential")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("MauiConfigId");

                    b.ToTable("MauiConfig");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dsstats.db.PlayerRating", b =>
                {
                    b.Property<int>("PlayerRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Change")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double>("Consistency")
                        .HasColumnType("REAL");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastGame")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<int>("Main")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mvps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("RatingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerRatingId");

                    b.HasIndex("LastGame");

                    b.HasIndex("Rating");

                    b.HasIndex("RatingType");

                    b.HasIndex("PlayerId", "RatingType")
                        .IsUnique();

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.Property<int>("PlayerUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gameloop")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReplayPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerUpgradeId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("UpgradeId");

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Property<int>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseBuild")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bunker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cannon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompatHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MiddleChanges")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplayHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Uploaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayId");

                    b.HasIndex("CompatHash");

                    b.HasIndex("Gametime");

                    b.HasIndex("ReplayHash")
                        .IsUnique();

                    b.HasIndex("Gametime", "ReplayId");

                    b.HasIndex("Gametime", "Duration", "WinnerTeam", "PlayerCount", "GameMode", "TE");

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("dsstats.db.ReplayArcadeMatch", b =>
                {
                    b.Property<int>("ReplayArcadeMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchTime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayArcadeMatchId");

                    b.ToTable("ReplayArcadeMatches");
                });

            modelBuilder.Entity("dsstats.db.ReplayIdResult", b =>
                {
                    b.Property<string>("ReplayIdsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeqKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("ReplayIdResult");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Property<int>("ReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Apm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clan")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMvp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUploader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Messages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OppRace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Refineries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedRace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("TierUpgrades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReplayPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerRating", b =>
                {
                    b.Property<int>("ReplayPlayerRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExpectedDelta")
                        .HasPrecision(7, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RatingBefore")
                        .HasPrecision(7, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("RatingDelta")
                        .HasPrecision(7, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("RatingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReplayRatingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayPlayerRatingId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("ReplayRatingId", "ReplayPlayerId", "RatingType")
                        .IsUnique();

                    b.ToTable("ReplayPlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.Property<int>("ReplayRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvgRating")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExpectedWinProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPreRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeaverType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayRatingId");

                    b.HasIndex("IsPreRating");

                    b.HasIndex("ReplayId", "RatingType")
                        .IsUnique();

                    b.ToTable("ReplayRatings");
                });

            modelBuilder.Entity("dsstats.db.ReplayUploadJob", b =>
                {
                    b.Property<int>("ReplayUploadJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlobFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.HasKey("ReplayUploadJobId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinishedAt");

                    b.ToTable("ReplayUploadJobs");
                });

            modelBuilder.Entity("dsstats.db.Sc2Profile", b =>
                {
                    b.Property<int>("Sc2ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MauiConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Sc2ProfileId");

                    b.HasIndex("MauiConfigId");

                    b.HasIndex("Name");

                    b.ToTable("Sc2Profiles");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Property<int>("SpawnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Breakpoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilledValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeSpent")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpawnId");

                    b.HasIndex("ReplayPlayerId");

                    b.ToTable("Spawns");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.Property<int>("SpawnUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Positions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpawnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpawnUnitId");

                    b.HasIndex("SpawnId");

                    b.HasIndex("UnitId");

                    b.ToTable("SpawnUnits");
                });

            modelBuilder.Entity("dsstats.db.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("UnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.BonusDamage", b =>
                {
                    b.Property<int>("BonusDamageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DsWeaponId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerUpgrade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("BonusDamageId");

                    b.HasIndex("DsWeaponId");

                    b.ToTable("BonusDamages");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsAbility", b =>
                {
                    b.Property<int>("DsAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityTarget")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AoeRadius")
                        .HasColumnType("REAL");

                    b.Property<int>("CastRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Commander")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(310)
                        .HasColumnType("TEXT");

                    b.Property<float>("EnergyCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("GlobalTimer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DsAbilityId");

                    b.ToTable("DsAbilities");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUnit", b =>
                {
                    b.Property<int>("DsUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Commander")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EnergyRegen")
                        .HasColumnType("REAL");

                    b.Property<float>("HealthRegen")
                        .HasColumnType("REAL");

                    b.Property<int>("Life")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapUnitType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShieldArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shields")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Speed")
                        .HasColumnType("REAL");

                    b.Property<int>("StartingEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("DsUnitId");

                    b.ToTable("DsUnits");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUpgrade", b =>
                {
                    b.Property<int>("DsUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Commander")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DsUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Upgrade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DsUpgradeId");

                    b.HasIndex("DsUnitId");

                    b.ToTable("DsUpgrades");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsWeapon", b =>
                {
                    b.Property<int>("DsWeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("Attacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamagePerUpgrade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DsUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("Range")
                        .HasColumnType("REAL");

                    b.HasKey("DsWeaponId");

                    b.HasIndex("DsUnitId");

                    b.ToTable("DsWeapons");
                });

            modelBuilder.Entity("dsstats.db.Upgrade", b =>
                {
                    b.Property<int>("UpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UpgradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.UploadJob", b =>
                {
                    b.Property<int>("UploadJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlobFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("UploadJobId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinishedAt");

                    b.ToTable("UploadJobs");
                });

            modelBuilder.Entity("DsAbilityDsUnit", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsAbility", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesDsAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.UnitModels.DsUnit", null)
                        .WithMany()
                        .HasForeignKey("DsUnitsDsUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.ArcadeReplay", "ArcadeReplay")
                        .WithMany("Players")
                        .HasForeignKey("ArcadeReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcadeReplay");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayRating", b =>
                {
                    b.HasOne("dsstats.db.ArcadeReplay", "ArcadeReplay")
                        .WithMany()
                        .HasForeignKey("ArcadeReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcadeReplay");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Realm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Region")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerId");

                            b1.HasIndex("Region", "Realm", "Id")
                                .IsUnique();

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("ToonId")
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.PlayerRating", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("ReplayPlayerId");

                    b.HasOne("dsstats.db.Upgrade", "Upgrade")
                        .WithMany()
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upgrade");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("ReplayPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Players")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerRating", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Ratings")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayRating", "ReplayRating")
                        .WithMany("ReplayPlayerRatings")
                        .HasForeignKey("ReplayRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ReplayPlayer");

                    b.Navigation("ReplayRating");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Ratings")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.Sc2Profile", b =>
                {
                    b.HasOne("dsstats.db.MauiConfig", "MauiConfig")
                        .WithMany("Sc2Profiles")
                        .HasForeignKey("MauiConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("Sc2ProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Realm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Region")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Sc2ProfileId");

                            b1.HasIndex("Region", "Realm", "Id");

                            b1.ToTable("Sc2Profiles");

                            b1.WithOwner()
                                .HasForeignKey("Sc2ProfileId");
                        });

                    b.Navigation("MauiConfig");

                    b.Navigation("ToonId")
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Spawns")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.HasOne("dsstats.db.Spawn", "Spawn")
                        .WithMany("Units")
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spawn");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.BonusDamage", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsWeapon", "DsWeapon")
                        .WithMany("BonusDamages")
                        .HasForeignKey("DsWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsWeapon");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUpgrade", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsUnit", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("DsUnitId");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsWeapon", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsUnit", "DsUnit")
                        .WithMany("Weapons")
                        .HasForeignKey("DsUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsUnit");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplay", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("dsstats.db.MauiConfig", b =>
                {
                    b.Navigation("Sc2Profiles");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Spawns");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.Navigation("ReplayPlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUnit", b =>
                {
                    b.Navigation("Upgrades");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsWeapon", b =>
                {
                    b.Navigation("BonusDamages");
                });
#pragma warning restore 612, 618
        }
    }
}
