// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dsstats.db;

#nullable disable

namespace dsstats.migrations.mysql.Migrations
{
    [DbContext(typeof(DsstatsContext))]
    [Migration("20250830152600_PlayerNameIndex")]
    partial class PlayerNameIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("dsstats.db.ArcadeReplay", b =>
                {
                    b.Property<int>("ArcadeReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArcadeReplayId"));

                    b.Property<long>("BnetBucketId")
                        .HasColumnType("bigint");

                    b.Property<long>("BnetRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("int");

                    b.HasKey("ArcadeReplayId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RegionId", "BnetBucketId", "BnetRecordId")
                        .IsUnique();

                    b.ToTable("ArcadeReplays");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayPlayer", b =>
                {
                    b.Property<int>("ArcadeReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArcadeReplayPlayerId"));

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("ArcadeReplayPlayerId");

                    b.HasIndex("ArcadeReplayId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ArcadeReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.CombinedReplay", b =>
                {
                    b.Property<int>("CombinedReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CombinedReplayId"));

                    b.Property<int?>("ArcadeReplayId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime>("Imported")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int?>("ReplayId")
                        .HasColumnType("int");

                    b.Property<bool>("TE")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("int");

                    b.HasKey("CombinedReplayId");

                    b.HasIndex("ArcadeReplayId")
                        .IsUnique();

                    b.HasIndex("Gametime");

                    b.HasIndex("Imported");

                    b.HasIndex("ReplayId")
                        .IsUnique();

                    b.ToTable("CombinedReplays");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dsstats.db.PlayerRating", b =>
                {
                    b.Property<int>("PlayerRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerRatingId"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double");

                    b.Property<double>("Consistency")
                        .HasColumnType("double");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<int>("Mvps")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("RatingType")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerRatingId");

                    b.HasIndex("Rating");

                    b.HasIndex("RatingType");

                    b.HasIndex("PlayerId", "RatingType")
                        .IsUnique();

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.Property<int>("PlayerUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerUpgradeId"));

                    b.Property<int>("Gameloop")
                        .HasColumnType("int");

                    b.Property<int?>("ReplayPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("int");

                    b.HasKey("PlayerUpgradeId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("UpgradeId");

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Property<int>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReplayId"));

                    b.Property<int>("BaseBuild")
                        .HasColumnType("int");

                    b.Property<int>("Bunker")
                        .HasColumnType("int");

                    b.Property<int>("Cannon")
                        .HasColumnType("int");

                    b.Property<string>("CompatHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.PrimitiveCollection<string>("MiddleChanges")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("ReplayHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("TE")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("int");

                    b.HasKey("ReplayId");

                    b.HasIndex("Gametime");

                    b.HasIndex("ReplayHash")
                        .IsUnique();

                    b.HasIndex("Gametime", "Duration", "WinnerTeam", "PlayerCount", "GameMode", "TE");

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("dsstats.db.ReplayArcadeMatch", b =>
                {
                    b.Property<int>("ReplayArcadeMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReplayArcadeMatchId"));

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("ReplayId")
                        .HasColumnType("int");

                    b.HasKey("ReplayArcadeMatchId");

                    b.ToTable("ReplayArcadeMatches");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Property<int>("ReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReplayPlayerId"));

                    b.Property<int>("Apm")
                        .HasColumnType("int");

                    b.Property<string>("Clan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GamePos")
                        .HasColumnType("int");

                    b.Property<bool>("IsMvp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUploader")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Messages")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("OppRace")
                        .HasColumnType("int");

                    b.Property<int>("Pings")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Race")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Refineries")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReplayId")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("SelectedRace")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("TierUpgrades")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReplayPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerRating", b =>
                {
                    b.Property<int>("ReplayPlayerRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReplayPlayerRatingId"));

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("RatingAfter")
                        .HasPrecision(7, 2)
                        .HasColumnType("double");

                    b.Property<double>("RatingBefore")
                        .HasPrecision(7, 2)
                        .HasColumnType("double");

                    b.Property<int>("RatingType")
                        .HasColumnType("int");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ReplayRatingId")
                        .HasColumnType("int");

                    b.HasKey("ReplayPlayerRatingId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("ReplayRatingId", "ReplayPlayerId", "RatingType")
                        .IsUnique();

                    b.ToTable("ReplayPlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.Property<int>("ReplayRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReplayRatingId"));

                    b.Property<int>("AvgRating")
                        .HasColumnType("int");

                    b.Property<double>("ExpectedWinProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("double");

                    b.Property<bool>("IsPreRating")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LeaverType")
                        .HasColumnType("int");

                    b.Property<int>("RatingType")
                        .HasColumnType("int");

                    b.Property<int>("ReplayId")
                        .HasColumnType("int");

                    b.HasKey("ReplayRatingId");

                    b.HasIndex("ReplayId", "RatingType")
                        .IsUnique();

                    b.ToTable("ReplayRatings");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Property<int>("SpawnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpawnId"));

                    b.Property<int>("ArmyValue")
                        .HasColumnType("int");

                    b.Property<int>("Breakpoint")
                        .HasColumnType("int");

                    b.Property<int>("GasCount")
                        .HasColumnType("int");

                    b.Property<int>("Income")
                        .HasColumnType("int");

                    b.Property<int>("KilledValue")
                        .HasColumnType("int");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeSpent")
                        .HasColumnType("int");

                    b.HasKey("SpawnId");

                    b.HasIndex("ReplayPlayerId");

                    b.ToTable("Spawns");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.Property<int>("SpawnUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpawnUnitId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Positions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SpawnId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("SpawnUnitId");

                    b.HasIndex("SpawnId");

                    b.HasIndex("UnitId");

                    b.ToTable("SpawnUnits");
                });

            modelBuilder.Entity("dsstats.db.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("UnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("dsstats.db.Upgrade", b =>
                {
                    b.Property<int>("UpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UpgradeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UpgradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.ArcadeReplay", "ArcadeReplay")
                        .WithMany("Players")
                        .HasForeignKey("ArcadeReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcadeReplay");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("Realm")
                                .HasColumnType("int");

                            b1.Property<int>("Region")
                                .HasColumnType("int");

                            b1.HasKey("PlayerId");

                            b1.HasIndex("Region", "Realm", "Id")
                                .IsUnique();

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("ToonId")
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.PlayerRating", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("ReplayPlayerId");

                    b.HasOne("dsstats.db.Upgrade", "Upgrade")
                        .WithMany()
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upgrade");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("ReplayPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Players")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerRating", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Ratings")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayRating", "ReplayRating")
                        .WithMany("ReplayPlayerRatings")
                        .HasForeignKey("ReplayRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ReplayPlayer");

                    b.Navigation("ReplayRating");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Ratings")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Spawns")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.HasOne("dsstats.db.Spawn", "Spawn")
                        .WithMany("Units")
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spawn");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplay", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Spawns");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.Navigation("ReplayPlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
