using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace dsstats.migrations.mysql.Migrations
{
    /// <inheritdoc />
    public partial class UnitInfo : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "MapUnitType",
                table: "DsUnits",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "UnitSize",
                table: "DsUnits",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.Sql(@"
                CREATE TEMPORARY TABLE UnitClassification (
                    Commander INT NOT NULL,
                    Name VARCHAR(100) NOT NULL,
                    MapUnitType INT NOT NULL,
                    UnitSize INT NOT NULL
                );
                ");


            migrationBuilder.Sql(@"
                INSERT INTO UnitClassification (Commander, Name, MapUnitType, UnitSize)
                VALUES
                (1, 'Adept', 1, 1),
                (1, 'Archon', 1, 3),
                (1, 'Carrier', 2, 3),
                (1, 'Colossus', 1, 3),
                (1, 'Dark Templar', 1, 1),
                (1, 'Disruptor', 1, 2),
                (1, 'High Templar', 1, 1),
                (1, 'Immortal', 1, 2),
                (1, 'Mothership', 2, 4),
                (1, 'Observer', 2, 1),
                (1, 'Oracle', 2, 2),
                (1, 'Phoenix', 2, 2),
                (1, 'Sentry', 1, 1),
                (1, 'Stalker', 1, 2),
                (1, 'Tempest', 2, 3),
                (1, 'Void Ray', 2, 2),
                (1, 'Zealot', 1, 1),
                (2, 'Banshee', 2, 2),
                (2, 'Battlecruiser', 2, 3),
                (2, 'Cyclone', 1, 2),
                (2, 'Ghost', 1, 1),
                (2, 'Hellbat', 1, 2),
                (2, 'Hellion', 1, 2),
                (2, 'Liberator', 2, 2),
                (2, 'Marauder', 1, 1),
                (2, 'Marine', 1, 1),
                (2, 'Medivac', 2, 2),
                (2, 'Raven', 2, 2),
                (2, 'Reaper', 1, 1),
                (2, 'Siege Tank', 1, 2),
                (2, 'Thor', 1, 2),
                (2, 'Viking', 2, 2),
                (2, 'Widow Mine', 1, 1),
                (3, 'Baneling', 1, 1),
                (3, 'Brood Lord', 2, 3),
                (3, 'Corruptor', 2, 2),
                (3, 'Hydralisk', 1, 1),
                (3, 'Infestor', 1, 2),
                (3, 'Lurker', 1, 2),
                (3, 'Mutalisk', 2, 1),
                (3, 'Overseer', 2, 2),
                (3, 'Queen', 1, 2),
                (3, 'Ravager', 1, 2),
                (3, 'Roach', 1, 1),
                (3, 'Swarm Host', 1, 2),
                (3, 'Ultralisk', 1, 2),
                (3, 'Viper', 2, 2),
                (3, 'Zergling', 1, 1),
                (10, 'Brutalisk', 1, 4),
                (10, 'Devourer', 2, 2),
                (10, 'Guardian', 2, 3),
                (10, 'Leviathan', 2, 4),
                (10, 'Locust', 1, 1),
                (10, 'Mutalisk', 2, 1),
                (10, 'Overseer', 2, 2),
                (10, 'Ravager', 1, 2),
                (10, 'Spine Crawler', 1, 1),
                (10, 'Spore Crawler', 1, 1),
                (10, 'Swarm Host', 1, 2),
                (10, 'Swarm Queen', 1, 3),
                (10, 'Toxic Nest', 1, 1),
                (10, 'Vile Roach', 1, 2),
                (10, 'Viper', 2, 2),
                (20, 'Alarak', 1, 3),
                (20, 'Ascendant', 1, 1),
                (20, 'Destroyer', 1, 2),
                (20, 'Havoc', 1, 1),
                (20, 'Photon Cannon', 1, 1),
                (20, 'Slayer', 1, 2),
                (20, 'Supplicant', 1, 1),
                (20, 'Tal''darim Mothership', 2, 4),
                (20, 'Vanguard', 1, 2),
                (20, 'War Prism', 2, 2),
                (20, 'Wrathwalker', 1, 3),
                (30, 'Dragoon', 1, 2),
                (30, 'High Archon', 1, 3),
                (30, 'High Templar', 1, 1),
                (30, 'Honor Guard', 1, 1),
                (30, 'Immortal', 1, 2),
                (30, 'Observer', 2, 1),
                (30, 'Phoenix', 2, 2),
                (30, 'Photon Cannon', 1, 1),
                (30, 'Purifier Tempest', 2, 3),
                (30, 'Reaver', 1, 2),
                (40, 'Creeper Host', 1, 2),
                (40, 'Dehaka', 1, 3),
                (40, 'Explosive Creeper', 1, 1),
                (40, 'Greater Primal Wurm', 1, 1),
                (40, 'Impaler', 1, 2),
                (40, 'Primal Guardian', 2, 3),
                (40, 'Primal Host', 1, 2),
                (40, 'Primal Hydralisk', 1, 1),
                (40, 'Primal Igniter', 1, 2),
                (40, 'Primal Locusts', 1, 1),
                (40, 'Primal Mutalisk', 2, 2),
                (40, 'Primal Roach', 1, 1),
                (40, 'Primal Ultralisk', 1, 3),
                (40, 'Primal Wurm', 1, 1),
                (40, 'Primal Zergling', 1, 1),
                (40, 'Ravasaur', 1, 1),
                (40, 'Tyrannozor', 1, 4),
                (50, 'Adept', 1, 1),
                (50, 'Carrier', 2, 3),
                (50, 'Clolarion', 2, 4),
                (50, 'Colossus', 1, 3),
                (50, 'Conservator', 1, 1),
                (50, 'Disruptor', 1, 2),
                (50, 'Fenix - Arbiter', 2, 3),
                (50, 'Fenix - Dragoon', 1, 3),
                (50, 'Fenix - Praetor', 1, 3),
                (50, 'Immortal', 1, 2),
                (50, 'Kaldalis', 1, 2),
                (50, 'Legionnaire', 1, 1),
                (50, 'Mojo', 2, 2),
                (50, 'Observer', 2, 1),
                (50, 'Photon Cannon', 1, 1),
                (50, 'Probius', 1, 1),
                (50, 'Scout', 2, 2),
                (50, 'Taldarin', 1, 1),
                (50, 'Talis', 1, 2),
                (50, 'Warbringer', 1, 2),
                (60, 'Assault Galleon', 2, 4),
                (60, 'Asteria Wraith', 2, 2),
                (60, 'Deimos Viking', 2, 2),
                (60, 'Hellbat', 1, 2),
                (60, 'Hellion', 1, 2),
                (60, 'Mag Mine', 1, 1),
                (60, 'Missile Turret', 1, 1),
                (60, 'Reaper', 1, 1),
                (60, 'Sovereign Battlecruiser', 2, 4),
                (60, 'Strike Fighter', 2, 2),
                (60, 'Theia Raven', 2, 2),
                (60, 'Widow Mine', 1, 1),
                (70, 'Annihilator', 1, 2),
                (70, 'Energizer', 1, 2),
                (70, 'Khaydarin Monolith', 1, 1),
                (70, 'Mirage', 2, 2),
                (70, 'Observer', 2, 1),
                (70, 'Photon Cannon', 1, 1),
                (70, 'Purifier Colossus', 1, 3),
                (70, 'Sentinel', 1, 1),
                (70, 'Shield Battery', 1, 1),
                (70, 'Support Carrier', 2, 3),
                (80, 'Brood Lord', 2, 3),
                (80, 'Brood Mutalisk', 2, 1),
                (80, 'Broodling', 1, 1),
                (80, 'Hydralisk', 1, 1),
                (80, 'Kerrigan', 1, 3),
                (80, 'Lurker', 1, 2),
                (80, 'Overseer', 2, 2),
                (80, 'Queen', 1, 2),
                (80, 'Raptorling', 1, 1),
                (80, 'Spine Crawler', 1, 1),
                (80, 'Spore Crawler', 1, 1),
                (80, 'Torrasque', 1, 3),
                (90, 'Aegis Guard', 1, 1),
                (90, 'Blackhammer', 1, 1),
                (90, 'Dominion Trooper', 1, 1),
                (90, 'Earthsplitter Ordnance', 1, 1),
                (90, 'Emperor''s Shadow', 1, 1),
                (90, 'Flamethrower Dominion Trooper', 1, 1),
                (90, 'Hailstorm Dominion Trooper', 1, 1),
                (90, 'Imperial Intercessor', 2, 2),
                (90, 'Imperial Witness', 2, 2),
                (90, 'LMG Dominion Trooper', 1, 1),
                (90, 'Missile Turret', 1, 1),
                (90, 'Mutalisk', 2, 1),
                (90, 'Pride of Augustgrad', 2, 4),
                (90, 'Shock Division', 1, 2),
                (90, 'Sky Fury', 2, 2),
                (90, 'Supply Bunker', 1, 1),
                (90, 'Ultralisk', 1, 2),
                (90, 'Warhound', 1, 2),
                (90, 'Zergling', 1, 1),
                (100, 'Covert Banshee', 2, 2),
                (100, 'Elite Marine', 1, 1),
                (100, 'Heavy Siege Tank', 1, 2),
                (100, 'Hellbat Ranger', 1, 2),
                (100, 'Holo Decoy', 1, 2),
                (100, 'Marauder Commando', 1, 2),
                (100, 'Missile Turret', 1, 1),
                (100, 'Nova', 1, 3),
                (100, 'Raid Liberator', 2, 2),
                (100, 'Railgun Turret', 1, 2),
                (100, 'Raven Type-II', 2, 2),
                (100, 'Spec Ops Ghost', 1, 1),
                (100, 'Strike Goliath', 1, 2),
                (110, 'Banshee', 2, 2),
                (110, 'Battlecruiser', 2, 3),
                (110, 'Bunker', 1, 1),
                (110, 'Dusk Wings', 2, 3),
                (110, 'Firebat', 1, 1),
                (110, 'Hyperion', 2, 4),
                (110, 'Marauder', 1, 1),
                (110, 'Marine', 1, 1),
                (110, 'Medic', 1, 1),
                (110, 'Missile Turret', 1, 1),
                (110, 'Siege Tank', 1, 2),
                (110, 'Spectre', 1, 1),
                (110, 'Spider Mine', 1, 1),
                (110, 'Viking', 2, 2),
                (110, 'Vulture', 1, 2),
                (120, 'Gary', 1, 3),
                (120, 'Mecha Baneling', 1, 1),
                (120, 'Mecha Battlecarrier Lord', 2, 3),
                (120, 'Mecha Broodling', 1, 1),
                (120, 'Mecha Corruptor', 2, 2),
                (120, 'Mecha Hydralisk', 1, 1),
                (120, 'Mecha Infestor', 1, 2),
                (120, 'Mecha Lurker', 1, 2),
                (120, 'Mecha Overseer', 2, 2),
                (120, 'Mecha Ravager', 1, 2),
                (120, 'Mecha Roach', 1, 1),
                (120, 'Mecha Spine Crawler', 1, 1),
                (120, 'Mecha Spore Crawler', 1, 1),
                (120, 'Mecha Ultralisk', 1, 2),
                (120, 'Mecha Zergling', 1, 1),
                (120, 'Super Gary', 1, 3),
                (130, 'Aleksander', 2, 4),
                (130, 'Apocalisk', 1, 4),
                (130, 'Brood Queen', 1, 2),
                (130, 'Infested Banshee', 2, 2),
                (130, 'Infested Bunker', 1, 3),
                (130, 'Infested Civilian', 1, 1),
                (130, 'Infested Diamondback', 1, 2),
                (130, 'Infested Liberator', 2, 2),
                (130, 'Infested Marine', 1, 1),
                (130, 'Infested Missile Turret', 1, 1),
                (130, 'Infested Siege Tank', 1, 2),
                (130, 'Overseer', 2, 2),
                (130, 'Volatile Infested', 1, 2),
                (140, 'A.R.E.S.', 1, 2),
                (140, 'Cyclone', 1, 2),
                (140, 'Devastation Turret', 1, 1),
                (140, 'Drakken Laser Drill', 1, 1),
                (140, 'Goliath', 1, 2),
                (140, 'Hellbat', 1, 2),
                (140, 'Missile Turret', 1, 1),
                (140, 'Science Vessel', 2, 2),
                (140, 'Siege Tank', 1, 2),
                (140, 'Thor', 1, 2),
                (140, 'Wraith', 2, 2),
                (150, 'Auto-Turret', 1, 1),
                (150, 'Crooked Sam', 1, 2),
                (150, 'James ""Sirius"" Sykes', 1, 2),
                (150, 'Kev ""Rattlesnake"" West', 1, 2),
                (150, 'Lt.Layna Nikara', 1, 2),
                (150, 'Miles ""Blaze"" Lewis', 1, 2),
                (150, 'Nux', 1, 2),
                (150, 'Rob ""Cannonball"" Boswell', 1, 2),
                (150, 'Tychus', 1, 3),
                (150, 'Vega', 1, 2),
                (150, 'Warhound Turret', 1, 1),
                (160, 'Centurion', 1, 1),
                (160, 'Corsair', 2, 2),
                (160, 'Dark Archon', 1, 2),
                (160, 'Dark Templar', 1, 1),
                (160, 'Oracle', 2, 2),
                (160, 'Photon Cannon', 1, 1),
                (160, 'Shadow Guard', 1, 1),
                (160, 'Stalker', 1, 2),
                (160, 'Void Ray', 2, 2),
                (170, 'Aberration', 1, 3),
                (170, 'Bile Launcher', 1, 1),
                (170, 'Corruptor', 2, 2),
                (170, 'Hunter Killer', 1, 2),
                (170, 'Overseer', 2, 2),
                (170, 'Queen', 1, 2),
                (170, 'Roach', 1, 1),
                (170, 'Scourge', 2, 1),
                (170, 'Spine Crawler', 1, 1),
                (170, 'Splitterling', 1, 1),
                (170, 'Splitterling Spawn', 1, 1),
                (170, 'Spore Crawler', 1, 1),
                (170, 'Swarmling', 1, 1),
                (170, 'Zagara', 1, 3),
                (180, 'Honor Guard', 1, 1),
                (180, 'Telbrus', 1, 1),
                (180, 'Void Templar', 1, 1),
                (180, 'Xel''Naga Abrogator', 1, 1),
                (180, 'Xel''Naga Ambusher', 1, 2),
                (180, 'Xel''Naga Enforcer', 1, 2),
                (180, 'Xel''Naga Shieldguard', 1, 1),
                (180, 'Xel''Naga Watcher', 1, 1),
                (180, 'Zeratul', 1, 3)
                ;");

            migrationBuilder.Sql(@"
                UPDATE DsUnits u
                JOIN UnitClassification m
                  ON u.Commander = m.Commander
                 AND u.Name = m.Name
                SET
                  u.MapUnitType = m.MapUnitType,
                  u.UnitSize = m.UnitSize;
                ");

            migrationBuilder.Sql(@"DROP TEMPORARY TABLE IF EXISTS UnitClassification;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "MapUnitType",
                table: "DsUnits");

            migrationBuilder.DropColumn(
                name: "UnitSize",
                table: "DsUnits");
        }
    }
}