using System.Collections.Frozen;

namespace dsstats.shared.Units;

public sealed record BuildUnitNg(string Name, Commander Commander, UnitSize Size, UnitColor Color, WeaponTarget MovementType);

public static partial class UnitMapNg
{
    public static string GetUnitColor(UnitColor unitColor) =>
        unitColor switch
        {
            UnitColor.Color1  => "#C0392B",
            UnitColor.Color2  => "#9B59B6",
            UnitColor.Color3  => "#2980B9",
            UnitColor.Color4  => "#1ABC9C",
            UnitColor.Color5  => "#F1C40F",
            UnitColor.Color6  => "#D35400",
            UnitColor.Color7  => "#ECF0F1",
            UnitColor.Color8  => "#7F8C8D",
            UnitColor.Color9  => "#943126",
            UnitColor.Color10 => "#5B2C6F",
            UnitColor.Color11 => "#21618C",
            UnitColor.Color12 => "#0E6655",
            UnitColor.Color13 => "#9C640C",
            UnitColor.Color14 => "#797D7F",
            UnitColor.Color15 => "#515A5A",
            _                 => "#F9EBEA"
        };

    public static (double radius, string color) GetColorAndRadius(string unitName, Commander commander)
    {
        if (_unitMap.TryGetValue((unitName, commander), out var unit))
        {
            var radius = unit.Size switch
            {
                UnitSize.VerySmall => 3,
                UnitSize.Small     => 6,
                UnitSize.Normal    => 10,
                UnitSize.Big       => 15,
                UnitSize.Hero      => 20,
                UnitSize.VeryBig   => 25,
                _                  => 12
            };

            if (unit.MovementType.HasFlag(WeaponTarget.Air))
            {
                radius += 2;
            }

            return (radius, GetUnitColor(unit.Color));
        }

        return (12, "#EC7063");
    }

    private static readonly FrozenDictionary<(string Name, Commander Commander), BuildUnitNg> _unitMap;

    static UnitMapNg()
    {
        _unitMap = _rawUnits
            .Select(u => new BuildUnitNg(u.Name, u.Commander, u.Size, u.Color, u.MovementType))
            .ToFrozenDictionary(u => (u.Name, u.Commander));
    }

    private static readonly (string Name, Commander Commander, UnitSize Size, UnitColor Color, WeaponTarget MovementType)[] _rawUnits =
    [
        // ── Protoss ──────────────────────────────────────────────────────────────
        ("Stalker",                              Commander.Protoss,  UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("Sentry",                               Commander.Protoss,  UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("Adept",                                Commander.Protoss,  UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("Observer",                             Commander.Protoss,  UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Air),
        ("VoidRay",                              Commander.Protoss,  UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("Disruptor",                            Commander.Protoss,  UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("Immortal",                             Commander.Protoss,  UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("HighTemplar",                          Commander.Protoss,  UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Ground),
        ("Mothership",                           Commander.Protoss,  UnitSize.VeryBig,   UnitColor.Color9,  WeaponTarget.Air),
        ("Carrier",                              Commander.Protoss,  UnitSize.Big,       UnitColor.Color10, WeaponTarget.Air),
        ("Archon",                               Commander.Protoss,  UnitSize.Big,       UnitColor.Color11, WeaponTarget.Ground),
        ("Zealot",                               Commander.Protoss,  UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("Colossus",                             Commander.Protoss,  UnitSize.Big,       UnitColor.Color13, WeaponTarget.Ground),
        ("Tempest",                              Commander.Protoss,  UnitSize.Big,       UnitColor.Color14, WeaponTarget.Air),
        ("Phoenix",                              Commander.Protoss,  UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Air),
        ("Oracle",                               Commander.Protoss,  UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Air),
        ("DarkTemplar",                          Commander.Protoss,  UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),

        // ── Terran ───────────────────────────────────────────────────────────────
        ("Reaper",                               Commander.Terran,   UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Ground),
        ("Marine",                               Commander.Terran,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("Marauder",                             Commander.Terran,   UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("Medivac",                              Commander.Terran,   UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Air),
        ("Raven",                                Commander.Terran,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("Viking",                               Commander.Terran,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("Thor",                                 Commander.Terran,   UnitSize.Big,       UnitColor.Color7,  WeaponTarget.Ground),
        ("SiegeTank",                            Commander.Terran,   UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Ground),
        ("Battlecruiser",                        Commander.Terran,   UnitSize.Big,       UnitColor.Color9,  WeaponTarget.Air),
        ("Liberator",                            Commander.Terran,   UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Air),
        ("WidowMine",                            Commander.Terran,   UnitSize.Small,     UnitColor.Color11, WeaponTarget.Ground),
        ("Banshee",                              Commander.Terran,   UnitSize.Normal,    UnitColor.Color12, WeaponTarget.Air),
        ("Ghost",                                Commander.Terran,   UnitSize.Small,     UnitColor.Color13, WeaponTarget.Ground),
        ("Hellion",                              Commander.Terran,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("Cyclone",                              Commander.Terran,   UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Ground),
        ("MarineLightweight",                    Commander.Terran,   UnitSize.VerySmall, UnitColor.Color1,  WeaponTarget.Ground),
        ("ThorAP",                               Commander.Terran,   UnitSize.Big,       UnitColor.Color2,  WeaponTarget.Ground),
        ("VikingFighter",                        Commander.Terran,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
        ("HellionTank",                          Commander.Terran,   UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Ground),
        ("GhostAlternate",                       Commander.Terran,   UnitSize.Small,     UnitColor.Color5,  WeaponTarget.Ground),
        ("GhostNova",                            Commander.Terran,   UnitSize.Small,     UnitColor.Color6,  WeaponTarget.Ground),
        ("VikingAssault",                        Commander.Terran,   UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),

        // ── Zerg ─────────────────────────────────────────────────────────────────
        ("Zergling",                             Commander.Zerg,     UnitSize.VerySmall, UnitColor.Color1,  WeaponTarget.Ground),
        ("Queen",                                Commander.Zerg,     UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Ground),
        ("Hydralisk",                            Commander.Zerg,     UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("Infestor",                             Commander.Zerg,     UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Ground),
        ("Corruptor",                            Commander.Zerg,     UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("BroodLord",                            Commander.Zerg,     UnitSize.Big,       UnitColor.Color6,  WeaponTarget.Air),
        ("Viper",                                Commander.Zerg,     UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("Mutalisk",                             Commander.Zerg,     UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Air),
        ("Roach",                                Commander.Zerg,     UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Ground),
        ("Overseer",                             Commander.Zerg,     UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Air),
        ("Baneling",                             Commander.Zerg,     UnitSize.VerySmall, UnitColor.Color11, WeaponTarget.Ground),
        ("Ultralisk",                            Commander.Zerg,     UnitSize.Big,       UnitColor.Color12, WeaponTarget.Ground),
        ("Lurker",                               Commander.Zerg,     UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("SwarmHost",                            Commander.Zerg,     UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("SwarmHostMP",                          Commander.Zerg,     UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Ground),
        ("Ravager",                              Commander.Zerg,     UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("ZerglingStetmann",                     Commander.Zerg,     UnitSize.VerySmall, UnitColor.Color2,  WeaponTarget.Ground),
        ("LurkerMP",                             Commander.Zerg,     UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Ground),
        ("LocustMPPrecursor",                    Commander.Zerg,     UnitSize.VerySmall, UnitColor.Color4,  WeaponTarget.Ground),

        // ── Abathur ───────────────────────────────────────────────────────────────
        ("VileRoach",                            Commander.Abathur,  UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Ground),
        ("Brutalisk",                            Commander.Abathur,  UnitSize.VeryBig,   UnitColor.Color2,  WeaponTarget.Ground),
        ("SwarmQueenStarlight",                  Commander.Abathur,  UnitSize.Big,       UnitColor.Color3,  WeaponTarget.Ground),
        ("GuardianStarlight",                    Commander.Abathur,  UnitSize.Big,       UnitColor.Color4,  WeaponTarget.Air),
        ("AbathurOverseer",                      Commander.Abathur,  UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("ViperAbathur",                         Commander.Abathur,  UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("SwarmHostMP",                          Commander.Abathur,  UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("AbathurMutalisk",                      Commander.Abathur,  UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Air),
        ("SwarmQueen",                           Commander.Abathur,  UnitSize.Big,       UnitColor.Color9,  WeaponTarget.Ground),
        ("SwarmHost",                            Commander.Abathur,  UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("Overseer",                             Commander.Abathur,  UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Air),
        ("Mutalisk",                             Commander.Abathur,  UnitSize.Small,     UnitColor.Color12, WeaponTarget.Air),
        ("Ravager",                              Commander.Abathur,  UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("LeviathanStarlight",                   Commander.Abathur,  UnitSize.VeryBig,   UnitColor.Color14, WeaponTarget.Air),
        ("DevourerStarlight",                    Commander.Abathur,  UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Air),
        ("RavagerAbathur",                       Commander.Abathur,  UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("Devourer",                             Commander.Abathur,  UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Air),
        ("Viper",                                Commander.Abathur,  UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
        ("Guardian",                             Commander.Abathur,  UnitSize.Big,       UnitColor.Color4,  WeaponTarget.Air),
        ("Leviathan",                            Commander.Abathur,  UnitSize.VeryBig,   UnitColor.Color5,  WeaponTarget.Air),

        // ── Alarak ────────────────────────────────────────────────────────────────
        ("Vanguard",                             Commander.Alarak,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("Alarak",                               Commander.Alarak,   UnitSize.Hero,      UnitColor.Color2,  WeaponTarget.Ground),
        ("Supplicant",                           Commander.Alarak,   UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("Havoc",                                Commander.Alarak,   UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("Slayer",                               Commander.Alarak,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("HeroAlarakWaveUnit",                   Commander.Alarak,   UnitSize.VerySmall, UnitColor.Color6,  WeaponTarget.Ground),
        ("SupplicantStarlight",                  Commander.Alarak,   UnitSize.Small,     UnitColor.Color7,  WeaponTarget.Ground),
        ("HavocStarlight",                       Commander.Alarak,   UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Ground),
        ("WarPrism",                             Commander.Alarak,   UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Air),
        ("Wrathwalker",                          Commander.Alarak,   UnitSize.Big,       UnitColor.Color10, WeaponTarget.Ground),
        ("Destroyer",                            Commander.Alarak,   UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Ground),
        ("AscendantStarlight",                   Commander.Alarak,   UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("MothershipTaldarim",                   Commander.Alarak,   UnitSize.VeryBig,   UnitColor.Color13, WeaponTarget.Air),
        ("Ascendant",                            Commander.Alarak,   UnitSize.Small,     UnitColor.Color14, WeaponTarget.Ground),

        // ── Artanis ───────────────────────────────────────────────────────────────
        ("Dragoon",                              Commander.Artanis,  UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("Observer",                             Commander.Artanis,  UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Air),
        ("HonorGuard",                           Commander.Artanis,  UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("Phoenix",                              Commander.Artanis,  UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Air),
        ("DragoonStarlight",                     Commander.Artanis,  UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("PurifierTempest",                      Commander.Artanis,  UnitSize.Big,       UnitColor.Color6,  WeaponTarget.Air),
        ("PhoenixArtanis",                       Commander.Artanis,  UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("HighArchon",                           Commander.Artanis,  UnitSize.Big,       UnitColor.Color8,  WeaponTarget.Ground),
        ("ArtanisObserver",                      Commander.Artanis,  UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Air),
        ("ImmortalArtanis",                      Commander.Artanis,  UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("HighTemplarArtanis",                   Commander.Artanis,  UnitSize.Small,     UnitColor.Color11, WeaponTarget.Ground),
        ("Immortal",                             Commander.Artanis,  UnitSize.Normal,    UnitColor.Color12, WeaponTarget.Ground),
        ("Reaver",                               Commander.Artanis,  UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("ReaverStarlight",                      Commander.Artanis,  UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("HighTemplar",                          Commander.Artanis,  UnitSize.Small,     UnitColor.Color15, WeaponTarget.Ground),

        // ── Dehaka ────────────────────────────────────────────────────────────────
        ("Dehaka",                               Commander.Dehaka,   UnitSize.Hero,      UnitColor.Color1,  WeaponTarget.Ground),
        ("PrimalHydralisk",                      Commander.Dehaka,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("PrimalMutalisk",                       Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
        ("DehakaHero",                           Commander.Dehaka,   UnitSize.Hero,      UnitColor.Color4,  WeaponTarget.Ground),
        ("DehakaTyrannozor",                     Commander.Dehaka,   UnitSize.VeryBig,   UnitColor.Color5,  WeaponTarget.Ground),
        ("Tyrannozor",                           Commander.Dehaka,   UnitSize.VeryBig,   UnitColor.Color6,  WeaponTarget.Ground),
        ("CreeperHost",                          Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("PrimalIgniter",                        Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Ground),
        ("PrimalHost",                           Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Ground),
        ("PrimalRavasaur",                       Commander.Dehaka,   UnitSize.Small,     UnitColor.Color10, WeaponTarget.Ground),
        ("PrimalZergling",                       Commander.Dehaka,   UnitSize.VerySmall, UnitColor.Color11, WeaponTarget.Ground),
        ("Impaler",                              Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color12, WeaponTarget.Ground),
        ("DehakaPrimalHydralisk",                Commander.Dehaka,   UnitSize.Small,     UnitColor.Color13, WeaponTarget.Ground),
        ("DehakaPrimalRoach",                    Commander.Dehaka,   UnitSize.Small,     UnitColor.Color14, WeaponTarget.Ground),
        ("DehakaPrimalRavasaur",                 Commander.Dehaka,   UnitSize.Small,     UnitColor.Color15, WeaponTarget.Ground),
        ("DehakaPrimalIgniter",                  Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("DehakaPrimalMutalisk",                 Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Air),
        ("DehakaCreeperHost",                    Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Ground),
        ("DehakaPrimalGuardian",                 Commander.Dehaka,   UnitSize.Big,       UnitColor.Color4,  WeaponTarget.Air),
        ("DehakaPrimalZergling",                 Commander.Dehaka,   UnitSize.VerySmall, UnitColor.Color5,  WeaponTarget.Ground),
        ("DehakaImpaler",                        Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("DehakaPrimalUltralisk",                Commander.Dehaka,   UnitSize.Big,       UnitColor.Color7,  WeaponTarget.Ground),
        ("DehakaPrimalHost",                     Commander.Dehaka,   UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Ground),
        ("PrimalUltralisk",                      Commander.Dehaka,   UnitSize.Big,       UnitColor.Color9,  WeaponTarget.Ground),
        ("PrimalRoach",                          Commander.Dehaka,   UnitSize.Small,     UnitColor.Color10, WeaponTarget.Ground),
        ("PrimalGuardian",                       Commander.Dehaka,   UnitSize.Big,       UnitColor.Color11, WeaponTarget.Air),
        ("DehakaPrimalHostLocust",               Commander.Dehaka,   UnitSize.VerySmall, UnitColor.Color12, WeaponTarget.Ground),
        ("StrikeWeaponryLevel2Dummy",            Commander.Dehaka,   UnitSize.VerySmall, UnitColor.Color13, WeaponTarget.Ground),
        ("LocustMPPrecursor",                    Commander.Dehaka,   UnitSize.VerySmall, UnitColor.Color14, WeaponTarget.Ground),

        // ── Fenix ─────────────────────────────────────────────────────────────────
        ("Legionnaire",                          Commander.Fenix,    UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Ground),
        ("PurifierAdept",                        Commander.Fenix,    UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("PurifierTalis",                        Commander.Fenix,    UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("PurifierImmortal",                     Commander.Fenix,    UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Ground),
        ("Kaldalis",                             Commander.Fenix,    UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("PurifierScout",                        Commander.Fenix,    UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("Mojo",                                 Commander.Fenix,    UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("PurifierObserver",                     Commander.Fenix,    UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Air),
        ("Walker",                               Commander.Fenix,    UnitSize.Big,       UnitColor.Color9,  WeaponTarget.Ground),
        ("PurifierCarrier",                      Commander.Fenix,    UnitSize.Big,       UnitColor.Color10, WeaponTarget.Air),
        ("FenixWalker",                          Commander.Fenix,    UnitSize.Big,       UnitColor.Color11, WeaponTarget.Ground),
        ("Taldarin",                             Commander.Fenix,    UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("Conservator",                          Commander.Fenix,    UnitSize.Small,     UnitColor.Color13, WeaponTarget.Ground),
        ("PurifierDisruptor",                    Commander.Fenix,    UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("FenixFlyer",                           Commander.Fenix,    UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Air),
        ("Warbringer",                           Commander.Fenix,    UnitSize.VeryBig,   UnitColor.Color1,  WeaponTarget.Ground),
        ("Clolarion",                            Commander.Fenix,    UnitSize.VeryBig,   UnitColor.Color2,  WeaponTarget.Air),
        ("PurifierInterceptor",                  Commander.Fenix,    UnitSize.VerySmall, UnitColor.Color3,  WeaponTarget.Air),
        ("FenixPraetor",                         Commander.Fenix,    UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Ground),
        ("Praetor",                              Commander.Fenix,    UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("PurifierColossus",                     Commander.Fenix,    UnitSize.Big,       UnitColor.Color6,  WeaponTarget.Air | WeaponTarget.Ground),
        ("Flyer",                                Commander.Fenix,    UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("PurifierColossusFenix",                Commander.Fenix,    UnitSize.Big,       UnitColor.Color8,  WeaponTarget.Air | WeaponTarget.Ground),
        ("Probius",                              Commander.Fenix,    UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Ground),

        // ── Horner ────────────────────────────────────────────────────────────────
        ("HornerAssaultGalleonUpgraded",         Commander.Horner,   UnitSize.VeryBig,   UnitColor.Color1,  WeaponTarget.Air),
        ("HornerWidowMine",                      Commander.Horner,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("AssaultGalleon",                       Commander.Horner,   UnitSize.VeryBig,   UnitColor.Color3,  WeaponTarget.Air),
        ("SovereignBattlecruiser",               Commander.Horner,   UnitSize.VeryBig,   UnitColor.Color4,  WeaponTarget.Air),
        ("HornerHellbat",                        Commander.Horner,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("HornerTheiaRaven",                     Commander.Horner,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("HornerAssaultGalleon",                 Commander.Horner,   UnitSize.VeryBig,   UnitColor.Color7,  WeaponTarget.Air),
        ("HornerDeimosVikingFighter",            Commander.Horner,   UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Air),
        ("HornerSovereignBattlecruiser",         Commander.Horner,   UnitSize.VeryBig,   UnitColor.Color9,  WeaponTarget.Air),
        ("HornerHellion",                        Commander.Horner,   UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("HornerStrikeFighter",                  Commander.Horner,   UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Air),
        ("HornerAsteriaWraith",                  Commander.Horner,   UnitSize.Normal,    UnitColor.Color12, WeaponTarget.Air),
        ("Hellbat",                              Commander.Horner,   UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("Hellion",                              Commander.Horner,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("TheiaRaven",                           Commander.Horner,   UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Air),
        ("AsteriaWraith",                        Commander.Horner,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Air),
        ("Reaper",                               Commander.Horner,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("DeimosViking",                         Commander.Horner,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
        ("WidowMine",                            Commander.Horner,   UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("StrikeFighter",                        Commander.Horner,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("HornerDeimosVikingAssault",            Commander.Horner,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("HornerReaper",                         Commander.Horner,   UnitSize.Small,     UnitColor.Color7,  WeaponTarget.Ground),
        ("HornerReaperKD8Charge",                Commander.Horner,   UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Ground),
        ("HornerReaperLD9ClusterCharges",        Commander.Horner,   UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Ground),

        // ── Karax ─────────────────────────────────────────────────────────────────
        ("AiurCarrier",                          Commander.Karax,    UnitSize.Big,       UnitColor.Color1,  WeaponTarget.Air),
        ("Mirage",                               Commander.Karax,    UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Air),
        ("Observer",                             Commander.Karax,    UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Air),
        ("Sentinel",                             Commander.Karax,    UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("Energizer",                            Commander.Karax,    UnitSize.Small,     UnitColor.Color5,  WeaponTarget.Ground),
        ("SentinelStarlight",                    Commander.Karax,    UnitSize.Small,     UnitColor.Color6,  WeaponTarget.Ground),
        ("Annihilator",                          Commander.Karax,    UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("PurifierColossus",                     Commander.Karax,    UnitSize.Big,       UnitColor.Color8,  WeaponTarget.Air | WeaponTarget.Ground),
        ("KaraxObserver",                        Commander.Karax,    UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Air),

        // ── Kerrigan ──────────────────────────────────────────────────────────────
        ("HeroKerriganWaveUnit",                 Commander.Kerrigan, UnitSize.VerySmall, UnitColor.Color1,  WeaponTarget.Ground),
        ("HydraliskKerrigan",                    Commander.Kerrigan, UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("RaptorlingLightweight",                Commander.Kerrigan, UnitSize.VerySmall, UnitColor.Color3,  WeaponTarget.Ground),
        ("BroodMutalisk",                        Commander.Kerrigan, UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Air),
        ("KerriganQueen",                        Commander.Kerrigan, UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("KerriganOverseer",                     Commander.Kerrigan, UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("LurkerMP",                             Commander.Kerrigan, UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("Torrasque",                            Commander.Kerrigan, UnitSize.Hero,      UnitColor.Color8,  WeaponTarget.Ground),
        ("BroodLordKerrigan",                    Commander.Kerrigan, UnitSize.Big,       UnitColor.Color9,  WeaponTarget.Air),
        ("Kerrigan",                             Commander.Kerrigan, UnitSize.Hero,      UnitColor.Color10, WeaponTarget.Ground),
        ("Overseer",                             Commander.Kerrigan, UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Air),
        ("Hydralisk",                            Commander.Kerrigan, UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("Lurker",                               Commander.Kerrigan, UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("Raptorling",                           Commander.Kerrigan, UnitSize.Small,     UnitColor.Color14, WeaponTarget.Ground),
        ("BroodLord",                            Commander.Kerrigan, UnitSize.Big,       UnitColor.Color15, WeaponTarget.Air),
        ("Queen",                                Commander.Kerrigan, UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("StrikeWeaponryLevel2Dummy",            Commander.Kerrigan, UnitSize.VerySmall, UnitColor.Color2,  WeaponTarget.Ground),

        // ── Mengsk ────────────────────────────────────────────────────────────────
        ("Marauder",                             Commander.Mengsk,   UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Ground),
        ("TrooperMengskFlamethrower",            Commander.Mengsk,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("Raven",                                Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
        ("SiegeTank",                            Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Ground),
        ("TrooperMengskAA",                      Commander.Mengsk,   UnitSize.Small,     UnitColor.Color5,  WeaponTarget.Ground),
        ("SkyFury",                              Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("TrooperMengskImproved",                Commander.Mengsk,   UnitSize.Small,     UnitColor.Color7,  WeaponTarget.Ground),
        ("Zergling",                             Commander.Mengsk,   UnitSize.VerySmall, UnitColor.Color8,  WeaponTarget.Ground),
        ("WarHound",                             Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Ground),
        ("ZerglingMengsk",                       Commander.Mengsk,   UnitSize.VerySmall, UnitColor.Color10, WeaponTarget.Ground),
        ("VikingMengskAssault",                  Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Ground),
        ("MarauderMengsk",                       Commander.Mengsk,   UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("GhostMengsk",                          Commander.Mengsk,   UnitSize.Small,     UnitColor.Color13, WeaponTarget.Ground),
        ("VikingMengskFighter",                  Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Air),
        ("TrooperMengsk",                        Commander.Mengsk,   UnitSize.Small,     UnitColor.Color15, WeaponTarget.Ground),
        ("MutaliskMengsk",                       Commander.Mengsk,   UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Air),
        ("ThorMengsk",                           Commander.Mengsk,   UnitSize.Big,       UnitColor.Color2,  WeaponTarget.Ground),
        ("UltraliskMengsk",                      Commander.Mengsk,   UnitSize.Big,       UnitColor.Color3,  WeaponTarget.Ground),
        ("RavenMengsk",                          Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Air),
        ("MedivacMengsk",                        Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("SiegeTankMengsk",                      Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("BattlecruiserMengsk",                  Commander.Mengsk,   UnitSize.Big,       UnitColor.Color7,  WeaponTarget.Air),
        ("Ghost",                                Commander.Mengsk,   UnitSize.Small,     UnitColor.Color8,  WeaponTarget.Ground),
        ("Ultralisk",                            Commander.Mengsk,   UnitSize.Big,       UnitColor.Color9,  WeaponTarget.Ground),
        ("Medivac",                              Commander.Mengsk,   UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Air),
        ("Trooper",                              Commander.Mengsk,   UnitSize.Small,     UnitColor.Color11, WeaponTarget.Ground),
        ("Mutalisk",                             Commander.Mengsk,   UnitSize.Small,     UnitColor.Color12, WeaponTarget.Air),
        ("Battlecruiser",                        Commander.Mengsk,   UnitSize.Big,       UnitColor.Color13, WeaponTarget.Air),
        ("Thor",                                 Commander.Mengsk,   UnitSize.Big,       UnitColor.Color14, WeaponTarget.Ground),
        ("StrikeWeaponryLevel2Dummy",            Commander.Mengsk,   UnitSize.VerySmall, UnitColor.Color15, WeaponTarget.Ground),

        // ── Nova ──────────────────────────────────────────────────────────────────
        ("MarauderCommando",                     Commander.Nova,     UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("SpecOpsGhost",                         Commander.Nova,     UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("RavenTypeII",                          Commander.Nova,     UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
        ("EliteMarine",                          Commander.Nova,     UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("StrikeGoliath",                        Commander.Nova,     UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("Nova",                                 Commander.Nova,     UnitSize.Hero,      UnitColor.Color6,  WeaponTarget.Ground),
        ("HellbatRanger",                        Commander.Nova,     UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("RaidLiberator",                        Commander.Nova,     UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Air),
        ("HeroNovaWaveUnit",                     Commander.Nova,     UnitSize.VerySmall, UnitColor.Color9,  WeaponTarget.Ground),
        ("HeavySiegeTank",                       Commander.Nova,     UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("CovertBanshee",                        Commander.Nova,     UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Air),
        ("HoloDecoy",                            Commander.Nova,     UnitSize.Normal,    UnitColor.Color12, WeaponTarget.Ground),
        ("StrikeWeaponryLevel1Dummy",            Commander.Nova,     UnitSize.VerySmall, UnitColor.Color13, WeaponTarget.Ground),
        ("RailgunTurret",                        Commander.Nova,     UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("NovaDefensiveDroneUnit",               Commander.Nova,     UnitSize.VerySmall, UnitColor.Color15, WeaponTarget.Air),

        // ── Raynor ────────────────────────────────────────────────────────────────
        ("Vulture",                              Commander.Raynor,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("DuskWing",                             Commander.Raynor,   UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Air),
        ("Battlecruiser",                        Commander.Raynor,   UnitSize.Big,       UnitColor.Color3,  WeaponTarget.Air),
        ("Viking",                               Commander.Raynor,   UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Air),
        ("Medic",                                Commander.Raynor,   UnitSize.Small,     UnitColor.Color5,  WeaponTarget.Ground),
        ("Banshee",                              Commander.Raynor,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("VultureStarlight",                     Commander.Raynor,   UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("MarineLightweight",                    Commander.Raynor,   UnitSize.VerySmall, UnitColor.Color8,  WeaponTarget.Ground),
        ("RaynorHyperion",                       Commander.Raynor,   UnitSize.VeryBig,   UnitColor.Color9,  WeaponTarget.Air),
        ("VikingFighter",                        Commander.Raynor,   UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Air),
        ("MedicStarlight",                       Commander.Raynor,   UnitSize.Small,     UnitColor.Color11, WeaponTarget.Ground),
        ("Marauder",                             Commander.Raynor,   UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("FirebatStarlight",                     Commander.Raynor,   UnitSize.Small,     UnitColor.Color13, WeaponTarget.Ground),
        ("SiegeTank",                            Commander.Raynor,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("BattlecruiserRaynor",                  Commander.Raynor,   UnitSize.Big,       UnitColor.Color15, WeaponTarget.Air),
        ("Marine",                               Commander.Raynor,   UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Ground),
        ("Firebat",                              Commander.Raynor,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("Hyperion",                             Commander.Raynor,   UnitSize.VeryBig,   UnitColor.Color3,  WeaponTarget.Air),
        ("SpiderMine",                           Commander.Raynor,   UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("VikingAssault",                        Commander.Raynor,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),

        // ── Stetmann ──────────────────────────────────────────────────────────────
        ("Baneling",                             Commander.Stetmann, UnitSize.VerySmall, UnitColor.Color1,  WeaponTarget.Ground),
        ("Gary",                                 Commander.Stetmann, UnitSize.Big,       UnitColor.Color2,  WeaponTarget.Ground),
        ("Zergling",                             Commander.Stetmann, UnitSize.VerySmall, UnitColor.Color3,  WeaponTarget.Ground),
        ("SuperGary",                            Commander.Stetmann, UnitSize.Big,       UnitColor.Color4,  WeaponTarget.Ground),
        ("Ultralisk",                            Commander.Stetmann, UnitSize.Big,       UnitColor.Color5,  WeaponTarget.Ground),
        ("SuperGaryStetmann",                    Commander.Stetmann, UnitSize.Big,       UnitColor.Color6,  WeaponTarget.Ground),
        ("OverseerStetmann",                     Commander.Stetmann, UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("CorruptorStetmann",                    Commander.Stetmann, UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Air),
        ("HydraliskStetmann",                    Commander.Stetmann, UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Ground),
        ("LurkerStetmann",                       Commander.Stetmann, UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("BanelingStetmann",                     Commander.Stetmann, UnitSize.VerySmall, UnitColor.Color11, WeaponTarget.Ground),
        ("GaryStetmann",                         Commander.Stetmann, UnitSize.Big,       UnitColor.Color12, WeaponTarget.Ground),
        ("ZerglingStetmann",                     Commander.Stetmann, UnitSize.VerySmall, UnitColor.Color13, WeaponTarget.Ground),
        ("InfestorStetmann",                     Commander.Stetmann, UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("UltraliskStetmann",                    Commander.Stetmann, UnitSize.Big,       UnitColor.Color15, WeaponTarget.Ground),
        ("BroodLordStetmann",                    Commander.Stetmann, UnitSize.Big,       UnitColor.Color1,  WeaponTarget.Air),
        ("InterceptorStetmann",                  Commander.Stetmann, UnitSize.VerySmall, UnitColor.Color2,  WeaponTarget.Air),
        ("Lurker",                               Commander.Stetmann, UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Ground),
        ("Hydralisk",                            Commander.Stetmann, UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("Corruptor",                            Commander.Stetmann, UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("Overseer",                             Commander.Stetmann, UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("Infestor",                             Commander.Stetmann, UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Ground),
        ("BroodLord",                            Commander.Stetmann, UnitSize.Big,       UnitColor.Color8,  WeaponTarget.Air),
        ("BroodlingStetmann",                    Commander.Stetmann, UnitSize.VerySmall, UnitColor.Color9,  WeaponTarget.Ground),

        // ── Stukov ────────────────────────────────────────────────────────────────
        ("InfestedBanshee",                      Commander.Stukov,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Air),
        ("InfestedBunker",                       Commander.Stukov,   UnitSize.Big,       UnitColor.Color2,  WeaponTarget.Ground),
        ("InfestedMarineStarlight",              Commander.Stukov,   UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("StukovInfestedBunker",                 Commander.Stukov,   UnitSize.Big,       UnitColor.Color4,  WeaponTarget.Ground),
        ("Overseer",                             Commander.Stukov,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("InfestedDiamondbackStarlight",         Commander.Stukov,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("InfestedBansheeStarlight",             Commander.Stukov,   UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("StukovAleksander",                     Commander.Stukov,   UnitSize.VeryBig,   UnitColor.Color8,  WeaponTarget.Air),
        ("BroodQueenStarlight",                  Commander.Stukov,   UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Ground),
        ("ApocaliskStarlight",                   Commander.Stukov,   UnitSize.VeryBig,   UnitColor.Color10, WeaponTarget.Ground),
        ("InfestedSiegeTankStarlight",           Commander.Stukov,   UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Ground),
        ("InfestedCivilian",                     Commander.Stukov,   UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("InfestedCivilianStarlight",            Commander.Stukov,   UnitSize.Small,     UnitColor.Color13, WeaponTarget.Ground),
        ("InfestedDiamondback",                  Commander.Stukov,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("Aleksander",                           Commander.Stukov,   UnitSize.VeryBig,   UnitColor.Color15, WeaponTarget.Air),
        ("VolatileInfestedStarlight",            Commander.Stukov,   UnitSize.Small,     UnitColor.Color1,  WeaponTarget.Ground),
        ("InfestedLiberatorStarlight",           Commander.Stukov,   UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Air),
        ("VolatileInfested",                     Commander.Stukov,   UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("InfestedMarine",                       Commander.Stukov,   UnitSize.Small,     UnitColor.Color4,  WeaponTarget.Ground),
        ("BroodQueen",                           Commander.Stukov,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("InfestedLiberator",                    Commander.Stukov,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("Apocalisk",                            Commander.Stukov,   UnitSize.VeryBig,   UnitColor.Color7,  WeaponTarget.Ground),
        ("InfestedSiegeTank",                    Commander.Stukov,   UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Ground),
        ("InfestedLiberatorViralSwarm",          Commander.Stukov,   UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Air),
        ("InfestedLiberatorStarlightViralSwarm", Commander.Stukov,   UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Air),
        ("StrikeWeaponryLevel3Dummy",            Commander.Stukov,   UnitSize.VerySmall, UnitColor.Color11, WeaponTarget.Ground),

        // ── Swann ─────────────────────────────────────────────────────────────────
        ("HellbatSwann",                         Commander.Swann,    UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("SwannCyclone",                         Commander.Swann,    UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Ground),
        ("GoliathStarlight",                     Commander.Swann,    UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Ground),
        ("ScienceVesselStarlight",               Commander.Swann,    UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Air),
        ("WraithStarlight",                      Commander.Swann,    UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("Hellbat",                              Commander.Swann,    UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("ScienceVessel",                        Commander.Swann,    UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("Cyclone",                              Commander.Swann,    UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Ground),
        ("SiegeTank",                            Commander.Swann,    UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Ground),
        ("Goliath",                              Commander.Swann,    UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("ARES",                                 Commander.Swann,    UnitSize.Normal,    UnitColor.Color11, WeaponTarget.Ground),
        ("Thor",                                 Commander.Swann,    UnitSize.Big,       UnitColor.Color12, WeaponTarget.Ground),
        ("SwannThor",                            Commander.Swann,    UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("Wraith",                               Commander.Swann,    UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Air),
        ("StrikeWeaponryLevel5Dummy",            Commander.Swann,    UnitSize.VerySmall, UnitColor.Color15, WeaponTarget.Ground),

        // ── Tychus ────────────────────────────────────────────────────────────────
        ("Blaze",                                Commander.Tychus,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("Vega",                                 Commander.Tychus,   UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Ground),
        ("Nikara",                               Commander.Tychus,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Ground),
        ("Tychus",                               Commander.Tychus,   UnitSize.Hero,      UnitColor.Color4,  WeaponTarget.Ground),
        ("TychusBlaze",                          Commander.Tychus,   UnitSize.Hero,      UnitColor.Color5,  WeaponTarget.Ground),
        ("TychusTychus",                         Commander.Tychus,   UnitSize.Hero,      UnitColor.Color6,  WeaponTarget.Ground),
        ("TychusNikara",                         Commander.Tychus,   UnitSize.Hero,      UnitColor.Color7,  WeaponTarget.Ground),
        ("TychusSam",                            Commander.Tychus,   UnitSize.Hero,      UnitColor.Color8,  WeaponTarget.Ground),
        ("TychusSirius",                         Commander.Tychus,   UnitSize.Hero,      UnitColor.Color9,  WeaponTarget.Ground),
        ("TychusCannonball",                     Commander.Tychus,   UnitSize.Hero,      UnitColor.Color10, WeaponTarget.Ground),
        ("TychusVega",                           Commander.Tychus,   UnitSize.Hero,      UnitColor.Color11, WeaponTarget.Ground),
        ("TychusRattlesnake",                    Commander.Tychus,   UnitSize.Hero,      UnitColor.Color12, WeaponTarget.Ground),
        ("Rattlesnake",                          Commander.Tychus,   UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("Sirius",                               Commander.Tychus,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("Cannonball",                           Commander.Tychus,   UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Ground),
        ("Sam",                                  Commander.Tychus,   UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Ground),
        ("TychusNux",                            Commander.Tychus,   UnitSize.Hero,      UnitColor.Color2,  WeaponTarget.Ground),
        ("Nux",                                  Commander.Tychus,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Ground),

        // ── Vorazun ───────────────────────────────────────────────────────────────
        ("Oracle",                               Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color1,  WeaponTarget.Air),
        ("Corsair",                              Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Air),
        ("DarkTemplar",                          Commander.Vorazun,  UnitSize.Small,     UnitColor.Color3,  WeaponTarget.Ground),
        ("Stalker",                              Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color4,  WeaponTarget.Ground),
        ("VoidRay",                              Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Air),
        ("StalkerVorazun",                       Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Ground),
        ("VorazunOracle",                        Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color7,  WeaponTarget.Air),
        ("VoidRayVorazun",                       Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color8,  WeaponTarget.Air),
        ("ShadowGuard",                          Commander.Vorazun,  UnitSize.Small,     UnitColor.Color9,  WeaponTarget.Ground),
        ("DarkArchonStarlight",                  Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color10, WeaponTarget.Ground),
        ("Centurion",                            Commander.Vorazun,  UnitSize.Small,     UnitColor.Color11, WeaponTarget.Ground),
        ("DarkTemplarVorazun",                   Commander.Vorazun,  UnitSize.Small,     UnitColor.Color12, WeaponTarget.Ground),
        ("DarkArchon",                           Commander.Vorazun,  UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Ground),
        ("StrikeWeaponryLevel1Dummy",            Commander.Vorazun,  UnitSize.VerySmall, UnitColor.Color14, WeaponTarget.Ground),

        // ── Zagara ────────────────────────────────────────────────────────────────
        ("HeroZagaraWaveUnit",                   Commander.Zagara,   UnitSize.VerySmall, UnitColor.Color1,  WeaponTarget.Ground),
        ("ZagaraQueen",                          Commander.Zagara,   UnitSize.Normal,    UnitColor.Color2,  WeaponTarget.Ground),
        ("Splitterling",                         Commander.Zagara,   UnitSize.VerySmall, UnitColor.Color3,  WeaponTarget.Ground),
        ("SwarmlingLightweight",                 Commander.Zagara,   UnitSize.VerySmall, UnitColor.Color4,  WeaponTarget.Ground),
        ("HunterKillerZagara",                   Commander.Zagara,   UnitSize.Normal,    UnitColor.Color5,  WeaponTarget.Ground),
        ("CorruptorZagara",                      Commander.Zagara,   UnitSize.Normal,    UnitColor.Color6,  WeaponTarget.Air),
        ("Swarmling",                            Commander.Zagara,   UnitSize.VerySmall, UnitColor.Color7,  WeaponTarget.Ground),
        ("Zagara",                               Commander.Zagara,   UnitSize.Hero,      UnitColor.Color8,  WeaponTarget.Ground),
        ("HunterKiller",                         Commander.Zagara,   UnitSize.Normal,    UnitColor.Color9,  WeaponTarget.Ground),
        ("Roach",                                Commander.Zagara,   UnitSize.Small,     UnitColor.Color10, WeaponTarget.Ground),
        ("Aberration",                           Commander.Zagara,   UnitSize.Big,       UnitColor.Color11, WeaponTarget.Ground),
        ("Scourge",                              Commander.Zagara,   UnitSize.VerySmall, UnitColor.Color12, WeaponTarget.Air),
        ("Corruptor",                            Commander.Zagara,   UnitSize.Normal,    UnitColor.Color13, WeaponTarget.Air),
        ("Queen",                                Commander.Zagara,   UnitSize.Normal,    UnitColor.Color14, WeaponTarget.Ground),
        ("OverseerZagara",                       Commander.Zagara,   UnitSize.Normal,    UnitColor.Color15, WeaponTarget.Air),
        ("InfestedAbomination",                  Commander.Zagara,   UnitSize.Big,       UnitColor.Color1,  WeaponTarget.Ground),
        ("ZagaraRoach",                          Commander.Zagara,   UnitSize.Small,     UnitColor.Color2,  WeaponTarget.Ground),
        ("Overseer",                             Commander.Zagara,   UnitSize.Normal,    UnitColor.Color3,  WeaponTarget.Air),
    ];
}
