// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dsstats.db;

#nullable disable

namespace dsstats.migrations.postgresql.Migrations
{
    [DbContext(typeof(DsstatsContext))]
    partial class DsstatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.Property<int>("PlayerUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerUpgradeId"));

                    b.Property<int>("Gameloop")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerUpgradeId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("UpgradeId");

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Property<int>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayId"));

                    b.Property<int>("BaseBuild")
                        .HasColumnType("integer");

                    b.Property<int>("Bunker")
                        .HasColumnType("integer");

                    b.Property<int>("Cannon")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.PrimitiveCollection<int[]>("MiddleChanges")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("integer");

                    b.HasKey("ReplayId");

                    b.HasIndex("ReplayHash")
                        .IsUnique();

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Property<int>("ReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayPlayerId"));

                    b.Property<int>("Apm")
                        .HasColumnType("integer");

                    b.Property<string>("Clan")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GamePos")
                        .HasColumnType("integer");

                    b.Property<int>("Messages")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Pings")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedRace")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("TierUpgrades")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("ReplayPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Property<int>("SpawnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpawnId"));

                    b.Property<int>("ArmyValue")
                        .HasColumnType("integer");

                    b.Property<int>("Breakpoint")
                        .HasColumnType("integer");

                    b.Property<int>("GasCount")
                        .HasColumnType("integer");

                    b.Property<int>("Income")
                        .HasColumnType("integer");

                    b.Property<int>("KilledValue")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeSpent")
                        .HasColumnType("integer");

                    b.HasKey("SpawnId");

                    b.HasIndex("ReplayPlayerId");

                    b.ToTable("Spawns");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.Property<int>("SpawnUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpawnUnitId"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Positions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SpawnId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("SpawnUnitId");

                    b.HasIndex("SpawnId");

                    b.HasIndex("UnitId");

                    b.ToTable("SpawnUnits");
                });

            modelBuilder.Entity("dsstats.db.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("UnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("dsstats.db.Upgrade", b =>
                {
                    b.Property<int>("UpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UpgradeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UpgradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("Realm")
                                .HasColumnType("integer");

                            b1.Property<int>("Region")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerId");

                            b1.HasIndex("Region", "Realm", "Id")
                                .IsUnique();

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("ToonId")
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("ReplayPlayerId");

                    b.HasOne("dsstats.db.Upgrade", "Upgrade")
                        .WithMany()
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upgrade");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("ReplayPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Players")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Spawns")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.HasOne("dsstats.db.Spawn", "Spawn")
                        .WithMany("Units")
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spawn");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Navigation("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Navigation("Spawns");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
