// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dsstats.db;

#nullable disable

namespace dsstats.migrations.postgresql.Migrations
{
    [DbContext(typeof(DsstatsContext))]
    partial class DsstatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DsAbilityDsUnit", b =>
                {
                    b.Property<int>("AbilitiesDsAbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("DsUnitsDsUnitId")
                        .HasColumnType("integer");

                    b.HasKey("AbilitiesDsAbilityId", "DsUnitsDsUnitId");

                    b.HasIndex("DsUnitsDsUnitId");

                    b.ToTable("DsAbilityDsUnit");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplay", b =>
                {
                    b.Property<int>("ArcadeReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArcadeReplayId"));

                    b.Property<long>("BnetBucketId")
                        .HasColumnType("bigint");

                    b.Property<long>("BnetRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("integer");

                    b.HasKey("ArcadeReplayId");

                    b.HasIndex("CreatedAt", "ArcadeReplayId")
                        .IsDescending(false, true);

                    b.HasIndex("RegionId", "BnetBucketId", "BnetRecordId")
                        .IsUnique();

                    b.ToTable("ArcadeReplays");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayPlayer", b =>
                {
                    b.Property<int>("ArcadeReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArcadeReplayPlayerId"));

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Team")
                        .HasColumnType("integer");

                    b.HasKey("ArcadeReplayPlayerId");

                    b.HasIndex("ArcadeReplayId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ArcadeReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayRating", b =>
                {
                    b.Property<int>("ArcadeReplayRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArcadeReplayRatingId"));

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("AvgRating")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedWinProbability")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("PlayerRatingDeltas")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("PlayerRatings")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("ArcadeReplayRatingId");

                    b.HasIndex("ArcadeReplayId");

                    b.ToTable("ArcadeReplayRatings");
                });

            modelBuilder.Entity("dsstats.db.CombinedReplay", b =>
                {
                    b.Property<int>("CombinedReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CombinedReplayId"));

                    b.Property<int?>("ArcadeReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplayId")
                        .HasColumnType("integer");

                    b.Property<bool>("TE")
                        .HasColumnType("boolean");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("integer");

                    b.HasKey("CombinedReplayId");

                    b.HasIndex("ArcadeReplayId")
                        .IsUnique();

                    b.HasIndex("Gametime");

                    b.HasIndex("Imported");

                    b.HasIndex("ReplayId")
                        .IsUnique();

                    b.ToTable("CombinedReplays");
                });

            modelBuilder.Entity("dsstats.db.InHouseDeviceLinkCode", b =>
                {
                    b.Property<int>("InHouseDeviceLinkCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InHouseDeviceLinkCodeId"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InHouseUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InHouseDeviceLinkCodeId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("InHouseUserId");

                    b.ToTable("InHouseDeviceLinkCodes");
                });

            modelBuilder.Entity("dsstats.db.InHouseGameSessionSimplified", b =>
                {
                    b.Property<int>("InHouseGameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InHouseGameSessionId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("CreatedByInHouseUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("ReplayIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("InHouseGameSessionId");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByInHouseUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("InHouseGameSessions", (string)null);
                });

            modelBuilder.Entity("dsstats.db.InHouseGameSessionStateSnapshot", b =>
                {
                    b.Property<int>("InHouseGameSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.HasKey("InHouseGameSessionId");

                    b.ToTable("InHouseGameSessionStateSnapshots");
                });

            modelBuilder.Entity("dsstats.db.InHousePasskeyCredential", b =>
                {
                    b.Property<int>("InHousePasskeyCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InHousePasskeyCredentialId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("InHouseUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("InHousePasskeyCredentialId");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("InHouseUserId");

                    b.HasIndex("UserHandle");

                    b.ToTable("InHousePasskeyCredentials");
                });

            modelBuilder.Entity("dsstats.db.InHouseProfile", b =>
                {
                    b.Property<int>("InHouseProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InHouseProfileId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InHouseUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("InHouseProfileId");

                    b.HasIndex("InHouseUserId");

                    b.ToTable("InHouseProfiles");
                });

            modelBuilder.Entity("dsstats.db.InHouseSession", b =>
                {
                    b.Property<int>("InHouseSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InHouseSessionId"));

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InHouseUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RefreshExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InHouseSessionId");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("InHouseUserId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("InHouseSessions");
                });

            modelBuilder.Entity("dsstats.db.InHouseUser", b =>
                {
                    b.Property<int>("InHouseUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InHouseUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("InHouseUserId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("InHouseUsers");
                });

            modelBuilder.Entity("dsstats.db.MauiConfig", b =>
                {
                    b.Property<int>("MauiConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MauiConfigId"));

                    b.Property<Guid>("AppGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoDecode")
                        .HasColumnType("boolean");

                    b.Property<int>("CPUCores")
                        .HasColumnType("integer");

                    b.Property<bool>("CheckForUpdates")
                        .HasColumnType("boolean");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("IgnoreReplays")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ReplayStartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionWindowGameMode")
                        .HasColumnType("integer");

                    b.Property<int>("SessionWindowHours")
                        .HasColumnType("integer");

                    b.Property<bool>("SessionWindowInitialized")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionWindowMode")
                        .HasColumnType("integer");

                    b.Property<int>("SessionWindowReplayCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadAskTime")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<bool>("UploadCredential")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("MauiConfigId");

                    b.ToTable("MauiConfig");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dsstats.db.PlayerRating", b =>
                {
                    b.Property<int>("PlayerRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerRatingId"));

                    b.Property<int>("ArcadeGames")
                        .HasColumnType("integer");

                    b.Property<int>("Change")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<double>("Consistency")
                        .HasColumnType("double precision");

                    b.Property<int>("DsstatsGames")
                        .HasColumnType("integer");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastGame")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("Main")
                        .HasColumnType("integer");

                    b.Property<int>("MainCount")
                        .HasColumnType("integer");

                    b.Property<int>("Mvps")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("RatingType")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("PlayerRatingId");

                    b.HasIndex("LastGame");

                    b.HasIndex("Rating");

                    b.HasIndex("RatingType");

                    b.HasIndex("PlayerId", "RatingType")
                        .IsUnique();

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.Property<int>("PlayerUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerUpgradeId"));

                    b.Property<int>("Gameloop")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerUpgradeId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("UpgradeId");

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Property<int>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayId"));

                    b.Property<int>("BaseBuild")
                        .HasColumnType("integer");

                    b.Property<int>("Bunker")
                        .HasColumnType("integer");

                    b.Property<int>("Cannon")
                        .HasColumnType("integer");

                    b.Property<string>("CompatHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Gametime")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("Imported")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.PrimitiveCollection<int[]>("MiddleChanges")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("TE")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Uploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("integer");

                    b.HasKey("ReplayId");

                    b.HasIndex("CompatHash");

                    b.HasIndex("Gametime");

                    b.HasIndex("ReplayHash")
                        .IsUnique();

                    b.HasIndex("Gametime", "ReplayId");

                    b.HasIndex("GameMode", "TE", "PlayerCount", "WinnerTeam", "Duration", "ReplayId");

                    b.HasIndex("Gametime", "Duration", "WinnerTeam", "PlayerCount", "GameMode", "TE");

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("dsstats.db.ReplayArcadeMatch", b =>
                {
                    b.Property<int>("ReplayArcadeMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayArcadeMatchId"));

                    b.Property<int>("ArcadeReplayId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MatchTime")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.HasKey("ReplayArcadeMatchId");

                    b.ToTable("ReplayArcadeMatches");
                });

            modelBuilder.Entity("dsstats.db.ReplayBuildDetail", b =>
                {
                    b.Property<int>("ReplayBuildDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayBuildDetailId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("DetectionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.HasKey("ReplayBuildDetailId");

                    b.HasIndex("ReplayId")
                        .IsUnique();

                    b.HasIndex("Status", "DetectionVersion");

                    b.ToTable("ReplayBuildDetails");
                });

            modelBuilder.Entity("dsstats.db.ReplayIdResult", b =>
                {
                    b.Property<string>("ReplayIdsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeqKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("ReplayIdResult");
                });

            modelBuilder.Entity("dsstats.db.ReplayObservers", b =>
                {
                    b.Property<int>("ReplayObserversId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayObserversId"));

                    b.PrimitiveCollection<int[]>("PlayerIds")
                        .HasColumnType("integer[]");

                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.HasKey("ReplayObserversId");

                    b.HasIndex("ReplayId")
                        .IsUnique();

                    b.ToTable("ReplayObservers");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Property<int>("ReplayPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayPlayerId"));

                    b.Property<int>("Apm")
                        .HasColumnType("integer");

                    b.Property<string>("Clan")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CompatHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GamePos")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMvp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUploader")
                        .HasColumnType("boolean");

                    b.Property<int>("Messages")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OppRace")
                        .HasColumnType("integer");

                    b.Property<int>("Pings")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Refineries")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedRace")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("TierUpgrades")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("ReplayPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerBuildDetail", b =>
                {
                    b.Property<int>("ReplayPlayerBuildDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayPlayerBuildDetailId"));

                    b.Property<int>("Build")
                        .HasColumnType("integer");

                    b.Property<int>("Commander")
                        .HasColumnType("integer");

                    b.Property<int>("GamePos")
                        .HasColumnType("integer");

                    b.Property<bool>("GasFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("Lane")
                        .HasColumnType("integer");

                    b.Property<int>("OppBuild")
                        .HasColumnType("integer");

                    b.Property<int>("OppCommander")
                        .HasColumnType("integer");

                    b.Property<int>("OppGamePos")
                        .HasColumnType("integer");

                    b.Property<bool>("OppGasFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("OppReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayBuildDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("ReplayPlayerBuildDetailId");

                    b.HasIndex("OppReplayPlayerId");

                    b.HasIndex("ReplayBuildDetailId");

                    b.HasIndex("ReplayPlayerId")
                        .IsUnique();

                    b.HasIndex("TeamId", "Lane");

                    b.HasIndex("Commander", "Build", "OppCommander", "OppBuild");

                    b.HasIndex("Commander", "Build", "TeamId", "Won");

                    b.ToTable("ReplayPlayerBuildDetails");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerRating", b =>
                {
                    b.Property<int>("ReplayPlayerRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayPlayerRatingId"));

                    b.Property<double>("ExpectedDelta")
                        .HasPrecision(7, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<double>("RatingBefore")
                        .HasPrecision(7, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("RatingDelta")
                        .HasPrecision(7, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("RatingType")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayRatingId")
                        .HasColumnType("integer");

                    b.HasKey("ReplayPlayerRatingId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayPlayerId");

                    b.HasIndex("ReplayRatingId", "ReplayPlayerId", "RatingType")
                        .IsUnique();

                    b.ToTable("ReplayPlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.Property<int>("ReplayRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayRatingId"));

                    b.Property<int>("AvgRating")
                        .HasColumnType("integer");

                    b.Property<double>("ExpectedWinProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPreRating")
                        .HasColumnType("boolean");

                    b.Property<int>("LeaverType")
                        .HasColumnType("integer");

                    b.Property<int>("RatingType")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.HasKey("ReplayRatingId");

                    b.HasIndex("IsPreRating");

                    b.HasIndex("ReplayId", "RatingType")
                        .IsUnique();

                    b.ToTable("ReplayRatings");
                });

            modelBuilder.Entity("dsstats.db.ReplaySpawnPlayback", b =>
                {
                    b.Property<int>("ReplayId")
                        .HasColumnType("integer");

                    b.Property<int>("CompressedLength")
                        .HasColumnType("integer");

                    b.Property<byte>("Compression")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("UncompressedLength")
                        .HasColumnType("integer");

                    b.Property<int>("UnitCount")
                        .HasColumnType("integer");

                    b.HasKey("ReplayId");

                    b.ToTable("ReplaySpawnPlaybacks");
                });

            modelBuilder.Entity("dsstats.db.ReplayTeamBuildDetail", b =>
                {
                    b.Property<int>("ReplayTeamBuildDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayTeamBuildDetailId"));

                    b.Property<int>("FollowerReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("LeaderReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayBuildDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBuild")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("ReplayTeamBuildDetailId");

                    b.HasIndex("FollowerReplayPlayerId");

                    b.HasIndex("LeaderReplayPlayerId");

                    b.HasIndex("ReplayBuildDetailId");

                    b.HasIndex("TeamBuild", "TeamId");

                    b.ToTable("ReplayTeamBuildDetails");
                });

            modelBuilder.Entity("dsstats.db.ReplayUploadJob", b =>
                {
                    b.Property<int>("ReplayUploadJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplayUploadJobId"));

                    b.Property<string>("BlobFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.HasKey("ReplayUploadJobId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinishedAt");

                    b.ToTable("ReplayUploadJobs");
                });

            modelBuilder.Entity("dsstats.db.Sc2Profile", b =>
                {
                    b.Property<int>("Sc2ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sc2ProfileId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MauiConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Sc2ProfileId");

                    b.HasIndex("MauiConfigId");

                    b.HasIndex("Name");

                    b.ToTable("Sc2Profiles");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Property<int>("SpawnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpawnId"));

                    b.Property<int>("ArmyValue")
                        .HasColumnType("integer");

                    b.Property<int>("Breakpoint")
                        .HasColumnType("integer");

                    b.Property<int>("GasCount")
                        .HasColumnType("integer");

                    b.Property<int>("Income")
                        .HasColumnType("integer");

                    b.Property<int>("KilledValue")
                        .HasColumnType("integer");

                    b.Property<int>("ReplayPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeSpent")
                        .HasColumnType("integer");

                    b.HasKey("SpawnId");

                    b.HasIndex("ReplayPlayerId");

                    b.ToTable("Spawns");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.Property<int>("SpawnUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpawnUnitId"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Positions")
                        .HasColumnType("integer[]");

                    b.Property<int>("SpawnId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("SpawnUnitId");

                    b.HasIndex("SpawnId");

                    b.HasIndex("UnitId");

                    b.ToTable("SpawnUnits");
                });

            modelBuilder.Entity("dsstats.db.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("UnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.BonusDamage", b =>
                {
                    b.Property<int>("BonusDamageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BonusDamageId"));

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DsWeaponId")
                        .HasColumnType("integer");

                    b.Property<int>("PerUpgrade")
                        .HasColumnType("integer");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("BonusDamageId");

                    b.HasIndex("DsWeaponId");

                    b.ToTable("BonusDamages");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsAbility", b =>
                {
                    b.Property<int>("DsAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DsAbilityId"));

                    b.Property<int>("AbilityTarget")
                        .HasColumnType("integer");

                    b.Property<float>("AoeRadius")
                        .HasColumnType("real");

                    b.Property<int>("CastRange")
                        .HasColumnType("integer");

                    b.Property<int>("Commander")
                        .HasColumnType("integer");

                    b.Property<int>("Cooldown")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(310)
                        .HasColumnType("character varying(310)");

                    b.Property<float>("EnergyCost")
                        .HasColumnType("real");

                    b.Property<bool>("GlobalTimer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DsAbilityId");

                    b.ToTable("DsAbilities");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUnit", b =>
                {
                    b.Property<int>("DsUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DsUnitId"));

                    b.Property<int>("Armor")
                        .HasColumnType("integer");

                    b.Property<int>("Commander")
                        .HasColumnType("integer");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<float>("EnergyRegen")
                        .HasColumnType("real");

                    b.Property<float>("HealthRegen")
                        .HasColumnType("real");

                    b.Property<int>("Life")
                        .HasColumnType("integer");

                    b.Property<int>("MapUnitType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShieldArmor")
                        .HasColumnType("integer");

                    b.Property<int>("Shields")
                        .HasColumnType("integer");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<int>("StartingEnergy")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("UnitSize")
                        .HasColumnType("integer");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("DsUnitId");

                    b.ToTable("DsUnits");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUpgrade", b =>
                {
                    b.Property<int>("DsUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DsUpgradeId"));

                    b.Property<int>("Commander")
                        .HasColumnType("integer");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("DsUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredTier")
                        .HasColumnType("integer");

                    b.Property<string>("Upgrade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DsUpgradeId");

                    b.HasIndex("DsUnitId");

                    b.ToTable("DsUpgrades");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsWeapon", b =>
                {
                    b.Property<int>("DsWeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DsWeaponId"));

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<int>("Attacks")
                        .HasColumnType("integer");

                    b.Property<int>("CanTarget")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DamagePerUpgrade")
                        .HasColumnType("integer");

                    b.Property<int>("DsUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Range")
                        .HasColumnType("real");

                    b.HasKey("DsWeaponId");

                    b.HasIndex("DsUnitId");

                    b.ToTable("DsWeapons");
                });

            modelBuilder.Entity("dsstats.db.Upgrade", b =>
                {
                    b.Property<int>("UpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UpgradeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UpgradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.UploadJob", b =>
                {
                    b.Property<int>("UploadJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UploadJobId"));

                    b.Property<string>("BlobFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.PrimitiveCollection<int[]>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Version")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("UploadJobId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinishedAt");

                    b.ToTable("UploadJobs");
                });

            modelBuilder.Entity("DsAbilityDsUnit", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsAbility", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesDsAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.UnitModels.DsUnit", null)
                        .WithMany()
                        .HasForeignKey("DsUnitsDsUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.ArcadeReplay", "ArcadeReplay")
                        .WithMany("Players")
                        .HasForeignKey("ArcadeReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcadeReplay");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplayRating", b =>
                {
                    b.HasOne("dsstats.db.ArcadeReplay", "ArcadeReplay")
                        .WithMany()
                        .HasForeignKey("ArcadeReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcadeReplay");
                });

            modelBuilder.Entity("dsstats.db.InHouseDeviceLinkCode", b =>
                {
                    b.HasOne("dsstats.db.InHouseUser", "User")
                        .WithMany("DeviceLinkCodes")
                        .HasForeignKey("InHouseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dsstats.db.InHouseGameSessionSimplified", b =>
                {
                    b.HasOne("dsstats.db.InHouseUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByInHouseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("dsstats.db.InHouseGameSessionStateSnapshot", b =>
                {
                    b.HasOne("dsstats.db.InHouseGameSessionSimplified", "Session")
                        .WithOne("StateSnapshot")
                        .HasForeignKey("dsstats.db.InHouseGameSessionStateSnapshot", "InHouseGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("dsstats.db.InHousePasskeyCredential", b =>
                {
                    b.HasOne("dsstats.db.InHouseUser", "User")
                        .WithMany("Passkeys")
                        .HasForeignKey("InHouseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dsstats.db.InHouseProfile", b =>
                {
                    b.HasOne("dsstats.db.InHouseUser", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("InHouseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("InHouseProfileId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("Realm")
                                .HasColumnType("integer");

                            b1.Property<int>("Region")
                                .HasColumnType("integer");

                            b1.HasKey("InHouseProfileId");

                            b1.HasIndex("Region", "Realm", "Id")
                                .IsUnique();

                            b1.ToTable("InHouseProfiles");

                            b1.WithOwner()
                                .HasForeignKey("InHouseProfileId");
                        });

                    b.Navigation("ToonId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dsstats.db.InHouseSession", b =>
                {
                    b.HasOne("dsstats.db.InHouseUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("InHouseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("Realm")
                                .HasColumnType("integer");

                            b1.Property<int>("Region")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerId");

                            b1.HasIndex("Region", "Realm", "Id")
                                .IsUnique();

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("ToonId")
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.PlayerRating", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("dsstats.db.PlayerUpgrade", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("ReplayPlayerId");

                    b.HasOne("dsstats.db.Upgrade", "Upgrade")
                        .WithMany()
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upgrade");
                });

            modelBuilder.Entity("dsstats.db.ReplayBuildDetail", b =>
                {
                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany()
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplayObservers", b =>
                {
                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany()
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany("ReplayPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Players")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerBuildDetail", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", "OppReplayPlayer")
                        .WithMany()
                        .HasForeignKey("OppReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayBuildDetail", "ReplayBuildDetail")
                        .WithMany("PlayerBuilds")
                        .HasForeignKey("ReplayBuildDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany()
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OppReplayPlayer");

                    b.Navigation("ReplayBuildDetail");

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayerRating", b =>
                {
                    b.HasOne("dsstats.db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Ratings")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayRating", "ReplayRating")
                        .WithMany("ReplayPlayerRatings")
                        .HasForeignKey("ReplayRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ReplayPlayer");

                    b.Navigation("ReplayRating");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithMany("Ratings")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplaySpawnPlayback", b =>
                {
                    b.HasOne("dsstats.db.Replay", "Replay")
                        .WithOne("SpawnPlayback")
                        .HasForeignKey("dsstats.db.ReplaySpawnPlayback", "ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("dsstats.db.ReplayTeamBuildDetail", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", "FollowerReplayPlayer")
                        .WithMany()
                        .HasForeignKey("FollowerReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayPlayer", "LeaderReplayPlayer")
                        .WithMany()
                        .HasForeignKey("LeaderReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.ReplayBuildDetail", "ReplayBuildDetail")
                        .WithMany("TeamBuilds")
                        .HasForeignKey("ReplayBuildDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowerReplayPlayer");

                    b.Navigation("LeaderReplayPlayer");

                    b.Navigation("ReplayBuildDetail");
                });

            modelBuilder.Entity("dsstats.db.Sc2Profile", b =>
                {
                    b.HasOne("dsstats.db.MauiConfig", "MauiConfig")
                        .WithMany("Sc2Profiles")
                        .HasForeignKey("MauiConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("dsstats.db.ToonId", "ToonId", b1 =>
                        {
                            b1.Property<int>("Sc2ProfileId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("Realm")
                                .HasColumnType("integer");

                            b1.Property<int>("Region")
                                .HasColumnType("integer");

                            b1.HasKey("Sc2ProfileId");

                            b1.HasIndex("Region", "Realm", "Id");

                            b1.ToTable("Sc2Profiles");

                            b1.WithOwner()
                                .HasForeignKey("Sc2ProfileId");
                        });

                    b.Navigation("MauiConfig");

                    b.Navigation("ToonId")
                        .IsRequired();
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.HasOne("dsstats.db.ReplayPlayer", "ReplayPlayer")
                        .WithMany("Spawns")
                        .HasForeignKey("ReplayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("dsstats.db.SpawnUnit", b =>
                {
                    b.HasOne("dsstats.db.Spawn", "Spawn")
                        .WithMany("Units")
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dsstats.db.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spawn");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.BonusDamage", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsWeapon", "DsWeapon")
                        .WithMany("BonusDamages")
                        .HasForeignKey("DsWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsWeapon");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUpgrade", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsUnit", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("DsUnitId");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsWeapon", b =>
                {
                    b.HasOne("dsstats.db.UnitModels.DsUnit", "DsUnit")
                        .WithMany("Weapons")
                        .HasForeignKey("DsUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsUnit");
                });

            modelBuilder.Entity("dsstats.db.ArcadeReplay", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("dsstats.db.InHouseGameSessionSimplified", b =>
                {
                    b.Navigation("StateSnapshot");
                });

            modelBuilder.Entity("dsstats.db.InHouseUser", b =>
                {
                    b.Navigation("DeviceLinkCodes");

                    b.Navigation("Passkeys");

                    b.Navigation("Profiles");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("dsstats.db.MauiConfig", b =>
                {
                    b.Navigation("Sc2Profiles");
                });

            modelBuilder.Entity("dsstats.db.Player", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("ReplayPlayers");
                });

            modelBuilder.Entity("dsstats.db.Replay", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Ratings");

                    b.Navigation("SpawnPlayback");
                });

            modelBuilder.Entity("dsstats.db.ReplayBuildDetail", b =>
                {
                    b.Navigation("PlayerBuilds");

                    b.Navigation("TeamBuilds");
                });

            modelBuilder.Entity("dsstats.db.ReplayPlayer", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Spawns");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("dsstats.db.ReplayRating", b =>
                {
                    b.Navigation("ReplayPlayerRatings");
                });

            modelBuilder.Entity("dsstats.db.Spawn", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsUnit", b =>
                {
                    b.Navigation("Upgrades");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("dsstats.db.UnitModels.DsWeapon", b =>
                {
                    b.Navigation("BonusDamages");
                });
#pragma warning restore 612, 618
        }
    }
}
