<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\dsstats.shared\dsstats.shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="s2protocol.NET" Version="0.9.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
