@dsstats.api_HostAddress = https://localhost:7048

GET {{dsstats.api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{dsstats.api_HostAddress}}/api/v1/arcade/getrequestnames/1

###

GET {{dsstats.api_HostAddress}}/api/v1/stats/dsupdates/1

###

GET {{dsstats.api_HostAddress}}/api/v1/builds/defaultplayers

###
