version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - /data:/data
      - ./db:/var/lib/mysql
      - ./certs:/certs
      - ./mysql:/etc/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: My_Root_Password_1
      MYSQL_DATABASE: dsstatstests
      MYSQL_USER: myuser
      MYSQL_PASSWORD: My_User_Password_1