name: Dsstats Tests
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create config
        run: |
          sudo mkdir -p /data/mysqlfiles \
          && sudo mkdir -p /data/temp \
          && sudo mkdir -p /data/ds/replayblobs \
          && sudo chmod 777 /data/mysqlfiles \
          && sudo chmod 777 /data/temp \
          && sudo chmod 777 /data/ds/replayblobs \
          && sudo cp ./src/tests/appsettings.Development.json /data/localserverconfig.json      
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./src/tests/docker/docker-compose.yml"
          services: mysql
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build ./src/tests/dsstats.ratings.tests/dsstats.ratings.tests.csproj
      - name: Run your tests
        run: dotnet test ./src/tests/dsstats.ratings.tests/dsstats.ratings.tests.csproj --no-build

